Changed includes; added debugging V2

diff --git a/bin/aecc-utils.in b/bin/aecc-utils.in
--- a/bin/aecc-utils.in
+++ b/bin/aecc-utils.in
@@ -1,20 +1,55 @@
 
+# print MSG if verbose=yes
+printVerbose()
+{
+    local MSG=$1
+    if [[ $verbose == "yes" ]]; then 
+        echo "aecc verbose: $MSG"
+    fi
+}
+
+# quick error check with message
+checkError()
+{
+    local CODE=$1
+    local MSG=$2
+    if (( $CODE )); then 
+        echo "aecc: $MSG"
+        exit $CODE
+    fi
+}
+
+# fail with message
+fail()
+{
+    local MSG=$1
+    echo "aecc: $MSG"
+    exit 1
+}   
+
 # find the location of this aecc script
-DIR="$( cd "$( dirname "$0" )" && pwd )"
-AECC_CFLAGS="@AECC_CFLAGS@ -I$DIR/../include"
+AESOP_HOME=$( cd $( dirname "$BASH_SOURCE" ) && cd .. && pwd )
+checkError $? "AESOP_HOME not found!"
+
+printVerbose "AESOP_HOME: $AESOP_HOME"
+
+AECC_CFLAGS="@AECC_CFLAGS@ -I$AESOP_HOME/../include"
 
 # the parsers can be in one of two locations; either in the same directory
 # as this script (if the tools have been installed) or in the ../parser
 # directory (if we are building in tree)
 
-if [ -x ${DIR}/ae-blocking-parser ]; then
-    AEPARSER=${DIR}/ae-blocking-parser
-elif [ -x ${DIR}/../parser/ae-blocking-parser ]; then
-    AEPARSER=${DIR}/../parser/ae-blocking-parser
-else
-    echo Unable to find ae-blocking-parser
-    exit 1
-fi
+AEPARSER=${AESOP_HOME}/bin/ae-blocking-parser
+[[ -x $AEPARSER ]] || fail "Unable to find ae-blocking-parser!"
+
+# if [ -x ${AESOP_HOME}/ae-blocking-parser ]; then
+#     AEPARSER=${AESOP_HOME}/ae-blocking-parser
+# elif [ -x ${AESOP_HOME}/../parser/ae-blocking-parser ]; then
+#     AEPARSER=${AESOP_HOME}/../parser/ae-blocking-parser
+# else
+#     echo Unable to find ae-blocking-parser
+#     exit 1
+# fi
     
 SPACES="                                                      "
 optind=0
@@ -506,7 +541,7 @@ runCmd()
     cmd=$@
     compilerout=$(mktemp tmp.XXXXXXXX)
     if test "$verbose" = "yes"; then
-        echo "$cmd"
+        echo "runCmd(): $cmd"
     fi
     $cmd > ${compilerout} 2>&1
     res=$?
@@ -535,6 +570,10 @@ doCPP()
     precompile="$1" ; shift
     ccopts=$@
 
+    if test "$verbose" = "yes"; then
+        echo "doCPP(): $cppinput"
+    fi
+
     jcppopt="-E"
     if test "${precompile}" = "yes"; then
         jcppopt="-D__blocking='' -Dpbranch='' -Dpwait='' -Dpbreak=''"
@@ -560,12 +599,16 @@ parseAesopSource()
     if test "${compileropts}" = "none"; then
         compileropts=""
     fi
-    
+
+    if test "$verbose" = "yes"; then
+        echo "parseAesopSource(): $input"
+    fi
+
     runCmd $verbose "Aesop parsing step failed: " \
            "${AEPARSER} -c ${compiler} ${popts} -r ${namedinput} -o ${output} -i ${input} -- ${AECC_CFLAGS} ${compileropts}"
     return $?
 }
-
+    
 # parseAesopHeader <verbose> <compiler> <input file> <output file> <named input> <parser opts> <compiler opts>
 parseAesopHeader()
 {
@@ -587,7 +630,7 @@ parseAesopHeader()
            "${AEPARSER} -c ${compiler} -j ${popts} -r ${namedinput} -o ${output} -i ${input} -- ${AECC_CFLAGS} ${compileropts}"
     return $?
 }
-    
+
 # parseRemoteSource <service name> <registry dir> <verbose> <compiler> <input file> <output file> <named input> <parser opts> <compiler opts>
 parseRemoteSource()
 {
@@ -628,6 +671,11 @@ parseRemoteSource()
         inputopt="${inputopt} -i ${_ifile}"
     done
 
+    if test "$verbose" = "yes"; then
+        echo "parseRemoteSource(): $input $AEPARSER"
+    fi
+
+    set -x
     runCmd $verbose "Aesop remote parsing failed: " \
            "${AERPARSER} ${serviceopts} ${regopts} -c ${compiler} ${popts} ${namedopt} ${outopt} ${inputopt} -- ${AECC_CFLAGS} ${compileropts}"
     return $?
@@ -649,3 +697,27 @@ doCompile()
            "${compiler} -x c -c -o ${outfile} ${AECC_CFLAGS} ${compileropts} ${infile}"
     return $?
 }
+
+doClean()
+# doClean <files>
+# Removes files as 'rm -f' w/o overriding permissions
+# Respects AESOP_CLEAN=0
+{
+    echo DOCLEAN $AESOP_CLEAN
+    for F in ${*}; do
+        if test "${AESOP_CLEAN}" != 0 ; then
+            if test -w ${F} ; then
+                rm ${F}
+            fi
+        else
+            if test "${AESOP_DEBUG}" = 1; then
+                echo "doClean: leaving ${F}"
+            fi
+        fi
+    done
+}
+
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 4
+# End:
diff --git a/bin/aecc.in b/bin/aecc.in
--- a/bin/aecc.in
+++ b/bin/aecc.in
@@ -1,10 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
 # find the location of this aecc script
-DIR="$( cd "$( dirname "$0" )" && pwd )"
+AESOP_HOME="$( cd "$( dirname "$0" )" && cd .. && pwd )"
+if [[ $? != 0 ]]; then
+    echo "aecc: could not find AESOP_HOME!"
+    exit 1
+fi
 
-# aecc utils should be in the same dir as aecc
-. ${DIR}/aecc-utils
+if [[ -n ${AESOP_DEBUG} ]]; then 
+    echo "AESOP_HOME: $AESOP_HOME"
+fi
+
+# aecc-utils should be in the same dir as aecc
+source ${AESOP_HOME}/bin/aecc-utils
+if [[ $? != 0 ]]; then
+    echo "aecc: could not find aecc-utils!"
+    exit 1
+fi
 
 setUsageMessage "Usage: aecc <options> <file> -- <compiler options>.  Specify --help for a list of options."
 
@@ -41,7 +53,7 @@ exitIfFailed()
 {
     res=$1
     if test $res -ne 0; then
-        rm -f ${clean}
+        doClean ${clean}
         exit $1
     fi
 }
@@ -100,7 +112,7 @@ if test "${hasOpt_from_interm}" != "yes"; then
 
     # if only source file (.c) or header (.h) was supposed to be generated, stop here
     if test "${hasOpt_just_source}" = "yes" || test "${hasOpt_parse_hae}" = "yes"; then
-        rm -f ${clean}
+        doClean ${clean}
         exit 0
     fi
 fi
@@ -117,7 +129,13 @@ fi
 doCompile ${verbose} ${compiler} ${compileinput} ${outputfile} ${COMPILEROPTS}
 exitIfFailed $?
 
-rm -f ${clean}
+doClean ${clean}
+
 exit 0
 
 # Done!
+
+# Local Variables:
+# mode: sh
+# sh-basic-offset: 4
+# End:
