Fixup for last commit

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -39,7 +39,7 @@ bindir = $(DESTDIR)@bindir@
 libdir = $(DESTDIR)@libdir@
 
 # tests
-TEST_RUNNER=@TEST_RUNNER@
+TEST_RUNNER=${builddir}/tests/testrunner.sh
 
 # tools
 A2X = @A2X@
@@ -148,8 +148,6 @@ HSSRC :=
 HSBINSRC :=
 TESTSRC :=
 PROGRAMSRC :=
-TEST_OUT :=
-TEST_RESULTS :=
 
 ASCIIDOCSRC :=
 
@@ -199,7 +197,7 @@ endif
 #    of a file that has the same name as the target.  Listing them
 #    here keeps make from accidentally doing too much work (see GNU
 #    make manual).
-.PHONY: all clean parserclean test_results
+.PHONY: all clean parserclean 
 
 ################################################################
 # Find project subdirectories
@@ -320,9 +318,6 @@ MCC_AER = $(call modcc,$(1))
 MCC_AE = $(call modcc,$(1))
 MCC_C = $(call modcc,$(1))
 
-# Get the parameters for a given test
-testparams = $(TESTPARAMS_$(1))
-
 # The object files for the triton library generated from .ae files
 AELIBOBJS=$(patsubst %.ae,%.o,$(AELIBSRC))
 aelibobjs: $(AELIBOBJS)
@@ -377,10 +372,6 @@ DEPENDS=$(TESTDEPS) $(GENLIBDEPS) $(LIBDEPS) $(AEDEPS) $(AESOP_TRHDR_DEPS) $(TES
 PROGRAMS = $(AEPROGRAM) $(PROGRAM)
 
 TESTS = $(AETEST) $(TEST)
-
-# TODO: Need a way to take mpiexec tests out of this
-runTESTS = $(patsubst %,run%,$(TESTS))
-runVALGRIND = $(patsubst %,valgrind%,$(TESTS))
 
 # for now we just use static if we're not on a mac
 ifneq (,$(USE_DYLIBS))
@@ -549,18 +540,9 @@ $(HSBIN): %: $(srcdir)/%.lhs $(HSSRC)
 
 all::  $(PROGRAMS) $(LIBRARIES)
 
-$(runTESTS): run%: %
-	@if test -n "$(call testparams,$<)"; then \
-		for p in $(call testparams,$<); do \
-			echo -n "Running $< $$p..."; \
-			$(TEST_RUNNER) ./$< $$p > /dev/null && echo OK || echo FAILED; \
-		done \
-	else \
-		echo -n "Running $<..."; \
-		$(TEST_RUNNER) ./$< > /dev/null && echo OK || echo FAILED;\
-	fi
-
-check: $(runTESTS) test_results
+.PHONY: check
+check: $(TESTS)
+	@$(TEST_RUNNER) -o ${builddir}/tests/test_results.tap $(TESTS)
 
 .PHONY: tests
 tests: test
@@ -568,39 +550,29 @@ tests: test
 .PHONY: test
 test: $(TESTS)
 
-test_results: $(TEST_RESULTS)
-
-$(runVALGRIND): valgrind%: %
-	@if test -n "$(call testparams,$<)"; then \
-		for p in $(call testparams,$<); do \
-			echo -n "Running valgrind $< $$p..."; \
-			valgrind --error-exitcode=1 ./$< $$p > /dev/null 2>./.vout; \
-			grep "All heap blocks were freed" ./.vout >/dev/null 2>&1; \
-			if test $$? != 0; then \
-				echo "\nErrors found in $<. Rerun valgrind ./$<"; \
-				exit 1; \
-			fi; \
-			echo "done."; \
-		done; \
-	else \
-		echo -n "Running valgrind $<..."; \
-		valgrind --error-exitcode=1 ./$< > /dev/null 2>./.vout; \
-		grep "All heap blocks were freed" ./.vout >/dev/null 2>&1; \
-		if test $$? != 0; then \
-			echo "\nErrors found in $<.  Rerun valgrind ./$<"; \
-			exit 1; \
-		fi; \
-		echo "done."; \
-	fi
-
-runvalgrind: $(runVALGRIND)
-
-%.result: % %.sh
-	$(Q) "  SH		$@"
-	$(E) SRCDIR=$(srcdir) $(srcdir)/$(patsubst %,%.sh,$<) > \
-		$*.tmp 2>&1
-	$(E) mv $*.tmp $@
-	$(E) echo -n "    		$@ : " && cat $@
+#$(runVALGRIND): valgrind%: %
+#	@if test -n "$(call testparams,$<)"; then \
+#		for p in $(call testparams,$<); do \
+#			echo -n "Running valgrind $< $$p..."; \
+#			valgrind --error-exitcode=1 ./$< $$p > /dev/null 2>./.vout; \
+#			grep "All heap blocks were freed" ./.vout >/dev/null 2>&1; \
+#			if test $$? != 0; then \
+#				echo "\nErrors found in $<. Rerun valgrind ./$<"; \
+#				exit 1; \
+#			fi; \
+#			echo "done."; \
+#		done; \
+#	else \
+#		echo -n "Running valgrind $<..."; \
+#		valgrind --error-exitcode=1 ./$< > /dev/null 2>./.vout; \
+#		grep "All heap blocks were freed" ./.vout >/dev/null 2>&1; \
+#		if test $$? != 0; then \
+#			echo "\nErrors found in $<.  Rerun valgrind ./$<"; \
+#			exit 1; \
+#		fi; \
+#		echo "done."; \
+#	fi
+#
 
 # other intermediates may exist from aecc and aercc
 INTERM_AESRC=$(patsubst %.o,%.ae.s,$(AEOBJS))
@@ -615,7 +587,7 @@ clean:: docclean
 	$(Q) "  CLEAN"
 	$(E)rm -f $(AEOBJS) $(LIBOBJS) $(GENLIBOBJS) $(AETEST) $(AEPROGRAM) $(TEST) $(PROGRAM) \
 	        $(AESOP_TRHDR) $(TESTLIBOBJS) \
-	        $(LIBRARIES) $(TEST_LIBRARIES) $(DEPENDS) $(TEST_RESULTS) $(TEST_OUT) \
+	        $(LIBRARIES) $(TEST_LIBRARIES) $(DEPENDS) \
                 $(INTERM)
 
 parserclean::
